Models in Domain en Database met mapping voor de Database objecten
MstrShine/OOSE-ICDE pull request #1
Opened 2023-11-30 14:09 UTC by MstrShine

2023-12-06 15:59 UTC, BV1BV1 requested changes

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/AssessmentCriteria.cs
> +
Graag alleen een lijst met Gradedescription collectionIds, niet alle bijbehorende objecten. Dit doen we consistent in het hele programma.

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/AssessmentDimension.cs
> +        public List<AssessmentCriteria> Criterias { get; set; }
Ook hier een lijst met criteria_collection_ids ipv een lijst met alle objecten.

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/Course.cs
> +
We laten elke parent de ids van de kinderen die erbij horen opslaan. We slaan niet ook de ids van de parent op bij het kind. Ik stel daarom voor dat we de studie waartoe een cursus behoort niet opslaan bij de cursus. Misschien kunnen we het begrip cursus wel helemaal weglaten...

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/Course.cs
> +    }
We slaan dus geen lijsten op met objecten, maar lijsten met strings: alleen de ids van de collections. Ipv een heel courseplanning object gewoon alleen de course planning collection id.

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/Course.cs
> +        public int CTE { get; set; }
Nog toevoegen: courseName en courseDescription

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/CoursePlanning.cs
> +    }
Broken records, maar dus geen hele objecten maar alleen de IDs voor de collections.

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/Exam.cs
> +    }
Geen lijsten met objecten, maar lijsten met collection_ids.

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/LearningOutcomeUnit.cs
> +    }
Lijsten met collection ids ipv hele objecten.

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/Lesson.cs
> +        public List<LearningOutcome> LearningOutcomes { get; set; }
Ook hier dus een lijst met learning outcome collection ids ipv hele objecten.

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/User.cs
> +    }
Wilden we niet nog een flag voor role toevoegen? Teacher of student?

2023-12-06 15:59 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Persistency.Database.Domain/AssessmentCriteria.cs
> +{
Alle opmerkingen die ik hierboven geplaatst heb gelden ook voor deze map heh...

2023-12-07 13:58 UTC, MstrShine commented on HAN.OOSE.ICDE.Domain/Course.cs
> +
Ik snap deze zin niet helemaal. Zou je dit kunnen verduidelijken

2023-12-07 18:20 UTC, BV1BV1 commented on HAN.OOSE.ICDE.Domain/Course.cs
> +
Net zoals de examens een soort van onder de EvL hangen en de beoordelingsdimensies onder de examens hangen ook de cursussen onder de studies. Als we studie/studyProgram als concept willen modelleren dan lijkt het logisch dat we studyProgram een lijst van cursus-collection-ids geven. Niet dat we van alle cursussen de id van de overkoepelende studie opslaan.

2023-12-07 19:38 UTC, merged